#!/usr/bin/env python3
"""
LLM Gatekeeper — signal validation layer for the signal engine.

Intercepts BUY signals produced by the backtested strategy pipeline and
asks an LLM to APPROVE, REJECT, or MODIFY each one before execution.

Design principles:
  - Fail-open: if the LLM is unavailable or times out, all signals pass through
    unchanged. The system degrades to its current rules-based behaviour.
  - SELL signals are NEVER gated. Exit overlay, risk manager, and circuit
    breaker exits must execute without LLM latency.
  - Batch: all signals for a cycle are validated in ONE LLM call (not per-signal).
  - Audit: every signal gets a 'gatekeeper_decision' field added to it so the
    decision_context audit trail records the gate outcome.
  - Cache: identical (symbol, action, strength_bucket) tuples within 5 min
    reuse the prior verdict (avoids redundant calls when signals repeat).

Usage:
    from llm.llm_chain import LLMChain
    from llm.llm_gatekeeper import LLMGatekeeper

    chain = LLMChain(timeout=15, cache_ttl=300)
    gk = LLMGatekeeper(chain=chain)

    validated_signals = gk.validate_signals(
        signals=buy_signals,
        portfolio_state={"value": 1234.0, "cash": 400.0, "positions": {...}},
        regime_label="risk-on",
    )
"""

import json
import logging
import os
import time
from typing import Any, Dict, List, Optional

logger = logging.getLogger(__name__)

_GATEKEEPER_SYSTEM_PROMPT = (
    "You are Edoras Gate, a risk-aware signal validator for a crypto paper portfolio. "
    "You review trading signals generated by quantitative strategies and decide "
    "whether each one is appropriate to execute given the current market context. "
    "Always respond with valid JSON. Be concise and decisive."
)


# Strength buckets for cache keying (avoids cache misses on minor strength changes)
def _strength_bucket(strength: float) -> int:
    """Round strength to nearest 10 for cache key stability."""
    return int(round(strength / 10.0)) * 10


class GatekeeperDecision:
    APPROVE = "approve"
    REJECT = "reject"
    MODIFY = "modify"  # approve but adjust strength downward


class LLMGatekeeper:
    """
    Validates BUY signals via LLM before they reach the execution engine.

    Args:
        chain:          An LLMChain instance (shared with trading_agent).
        min_confidence: Reject signals where LLM confidence < this (default 0).
                        Set to 60 to apply a confidence floor.
        timeout_passthrough: If True (default), any exception or timeout causes
                        fail-open — all signals pass through unmodified.
    """

    def __init__(
        self,
        chain=None,
        min_confidence: int = 0,
        timeout_passthrough: bool = True,
    ):
        # Lazy-import to avoid circular dependencies
        if chain is None:
            from llm.llm_chain import LLMChain

            chain = LLMChain(
                system_prompt=_GATEKEEPER_SYSTEM_PROMPT,
                timeout=15,
                cache_ttl=300,  # 5-min cache
                max_tokens=1000,  # gatekeeper needs less than trading agent
                fallback_json={"decisions": []},
            )
        self.chain = chain
        self.min_confidence = min_confidence
        self.timeout_passthrough = timeout_passthrough

        # Simple in-process cache keyed on (symbol, action, strength_bucket)
        # to reuse decisions within a 5-minute window
        self._decision_cache: Dict[str, tuple] = {}  # key -> (decision_dict, expiry)
        self._cache_ttl = 300

    # ── Public interface ──────────────────────────────────────────────────────

    def validate_signals(
        self,
        signals: List[Dict],
        portfolio_state: Optional[Dict] = None,
        regime_label: str = "unknown",
    ) -> List[Dict]:
        """
        Validate a list of BUY signals. Returns the filtered/annotated list.

        SELL signals passed in are returned unchanged (should not be in this list
        but the method is defensive about it).

        On any error, returns the original signal list unmodified (fail-open).
        """
        if not signals:
            return signals

        # Separate SELLs (pass through) from BUYs (validate)
        sell_sigs = [s for s in signals if s.get("action", "").upper() != "BUY"]
        buy_sigs = [s for s in signals if s.get("action", "").upper() == "BUY"]

        if not buy_sigs:
            return signals  # nothing to gate

        # Check cache for each signal
        cache_hits: Dict[int, Dict] = {}
        uncached: List[int] = []  # indices into buy_sigs
        for i, sig in enumerate(buy_sigs):
            ck = self._cache_key(sig)
            cached = self._cache_get(ck)
            if cached is not None:
                cache_hits[i] = cached
                logger.debug(f"Gatekeeper cache hit: {sig['symbol']}")
            else:
                uncached.append(i)

        # Validate uncached signals via LLM
        llm_decisions: Dict[int, Dict] = {}
        if uncached:
            uncached_sigs = [buy_sigs[i] for i in uncached]
            try:
                llm_decisions = self._validate_via_llm(
                    uncached_sigs, portfolio_state or {}, regime_label
                )
                # Store results to cache
                for local_idx, global_idx in enumerate(uncached):
                    dec = llm_decisions.get(
                        local_idx, self._default_decision(buy_sigs[global_idx])
                    )
                    ck = self._cache_key(buy_sigs[global_idx])
                    self._cache_set(ck, dec)
            except Exception as e:
                logger.warning(
                    f"Gatekeeper LLM call failed — failing open: {e}"
                    if self.timeout_passthrough
                    else f"Gatekeeper error: {e}"
                )
                if self.timeout_passthrough:
                    # Fail-open: annotate all as approved without LLM
                    for sig in buy_sigs:
                        sig["gatekeeper_decision"] = GatekeeperDecision.APPROVE
                        sig["gatekeeper_reasoning"] = "LLM unavailable — fail-open"
                    return sell_sigs + buy_sigs
                raise

        # Merge cache hits + LLM decisions and apply to signals
        validated_buys: List[Dict] = []
        rejected_count = 0

        for i, sig in enumerate(buy_sigs):
            if i in cache_hits:
                decision_dict = cache_hits[i]
            else:
                local_idx = uncached.index(i)
                decision_dict = llm_decisions.get(
                    local_idx, self._default_decision(sig)
                )

            verdict = decision_dict.get("decision", GatekeeperDecision.APPROVE)
            confidence = decision_dict.get("confidence", 100)
            reasoning = decision_dict.get("reasoning", "")

            # Confidence floor check
            if self.min_confidence > 0 and confidence < self.min_confidence:
                verdict = GatekeeperDecision.REJECT
                reasoning = f"confidence {confidence} < min {self.min_confidence}"

            sig["gatekeeper_decision"] = verdict
            sig["gatekeeper_reasoning"] = reasoning
            sig["gatekeeper_confidence"] = confidence

            if verdict == GatekeeperDecision.REJECT:
                rejected_count += 1
                logger.info(f"Gatekeeper REJECT: {sig['symbol']} — {reasoning[:100]}")
                continue  # drop signal

            if verdict == GatekeeperDecision.MODIFY:
                # Reduce strength to confidence level (floor at 35)
                new_strength = max(
                    35.0, min(sig.get("strength", 50), float(confidence))
                )
                logger.info(
                    f"Gatekeeper MODIFY: {sig['symbol']} "
                    f"strength {sig['strength']:.0f} → {new_strength:.0f} — {reasoning[:80]}"
                )
                sig["strength"] = new_strength
                sig["reason"] += f" [gk:{reasoning[:60]}]"

            if verdict == GatekeeperDecision.APPROVE:
                logger.debug(f"Gatekeeper APPROVE: {sig['symbol']} (conf={confidence})")

            validated_buys.append(sig)

        if rejected_count:
            logger.info(
                f"Gatekeeper: {rejected_count}/{len(buy_sigs)} BUY signals rejected, "
                f"{len(validated_buys)} approved"
            )

        return sell_sigs + validated_buys

    # ── LLM interaction ───────────────────────────────────────────────────────

    def _validate_via_llm(
        self,
        signals: List[Dict],
        portfolio_state: Dict,
        regime_label: str,
    ) -> Dict[int, Dict]:
        """
        Send signals to the LLM for validation.
        Returns a dict mapping signal index → decision_dict.
        """
        prompt = self._build_prompt(signals, portfolio_state, regime_label)
        response = self.chain.call_with_parse(prompt)

        # Parse decisions list from response
        decisions_raw = response.get("decisions", [])
        result: Dict[int, Dict] = {}

        for raw in decisions_raw:
            idx = raw.get("signal_index")
            if idx is None:
                continue
            if not isinstance(idx, int) or idx < 0 or idx >= len(signals):
                continue
            result[idx] = {
                "decision": raw.get("decision", GatekeeperDecision.APPROVE).lower(),
                "confidence": int(raw.get("confidence", 75)),
                "reasoning": raw.get("reasoning", ""),
            }

        # Default-approve any signals the LLM didn't mention
        for i in range(len(signals)):
            if i not in result:
                result[i] = self._default_decision(signals[i])

        return result

    def _build_prompt(
        self,
        signals: List[Dict],
        portfolio_state: Dict,
        regime_label: str,
    ) -> str:
        lines = [
            "## CONTEXT",
            f"Market regime: {regime_label}",
            f"Portfolio value: ${portfolio_state.get('value', 0):.2f}",
            f"Cash available: ${portfolio_state.get('cash', 0):.2f}",
            "",
        ]

        # Current positions (brief)
        positions = portfolio_state.get("positions", {})
        if positions:
            lines.append("Current positions:")
            for sym, pos in list(positions.items())[:8]:
                pnl = pos.get("pnl_pct", 0)
                lines.append(f"  {sym}: ${pos.get('value', 0):.0f} ({pnl:+.1f}%)")
            lines.append("")

        # Signals to evaluate
        lines.append("## SIGNALS TO EVALUATE")
        lines.append(
            "For each signal below, decide: APPROVE, REJECT, or MODIFY.\n"
            "APPROVE: signal looks sound given regime and portfolio context.\n"
            "REJECT:  signal conflicts with regime, overlaps existing position, or lacks edge.\n"
            "MODIFY:  approve but reduce confidence (e.g. conflicting indicators).\n"
        )

        for i, sig in enumerate(signals):
            lines.append(
                f"[{i}] {sig['symbol']} BUY | strength={sig.get('strength', 0):.0f} "
                f"| strategy={sig.get('_strategy_name', 'unknown')} "
                f"| tf={sig.get('_timeframe', '?')} "
                f"| reason: {sig.get('reason', '')[:120]}"
            )

        lines.append("")
        lines.append("## RESPONSE FORMAT")
        lines.append("Respond ONLY with this JSON (no extra text):")
        lines.append("```json")
        lines.append("{")
        lines.append('  "decisions": [')
        lines.append("    {")
        lines.append('      "signal_index": 0,')
        lines.append('      "decision": "approve|reject|modify",')
        lines.append('      "confidence": 80,')
        lines.append('      "reasoning": "brief explanation (1 sentence)"')
        lines.append("    }")
        lines.append("  ]")
        lines.append("}")
        lines.append("```")
        lines.append("")
        lines.append(
            "Rules: confidence 0-100. For MODIFY, confidence sets the new strength floor. "
            "REJECT sparingly — only when the signal is clearly wrong for the current context."
        )

        return "\n".join(lines)

    # ── Cache helpers ─────────────────────────────────────────────────────────

    def _cache_key(self, sig: Dict) -> str:
        return f"{sig['symbol']}:{sig.get('action', 'BUY')}:{_strength_bucket(sig.get('strength', 0))}"

    def _cache_get(self, key: str) -> Optional[Dict]:
        entry = self._decision_cache.get(key)
        if entry and time.monotonic() < entry[1]:
            return entry[0]
        self._decision_cache.pop(key, None)
        return None

    def _cache_set(self, key: str, value: Dict):
        self._decision_cache[key] = (value, time.monotonic() + self._cache_ttl)

    @staticmethod
    def _default_decision(sig: Dict) -> Dict:
        return {
            "decision": GatekeeperDecision.APPROVE,
            "confidence": 75,
            "reasoning": "default approve (LLM did not address this signal)",
        }
