#!/bin/bash
# Edoras Daily Report Engine — Generate reports + deliver via Telegram
# Called by systemd timer: edoras-daily-reports.timer
set -euo pipefail

EDORAS_DIR="$HOME/.openclaw/workspace/projects/edoras"
REPORTS_DIR="$HOME/.openclaw/workspace/reports"
CHAT_ID="$TELEGRAM_CHAT_ID"
TODAY=$(date +%Y-%m-%d)
WEEK_TAG="weekly-$(date +%G)-W$(date +%V)"

cd "$EDORAS_DIR"

# Telegram bot token — set via systemd EnvironmentFile or env
if [ -z "${TELEGRAM_BOT_TOKEN:-}" ]; then
    echo "WARNING: TELEGRAM_BOT_TOKEN not set, reports won't be delivered to Telegram"
fi

echo "=== Edoras Daily Reports — $TODAY ==="

# Step 1: Generate all reports
echo "[1/2] Generating reports..."
python3 report_engine.py all

# Step 2: Deliver via Telegram (send as document attachments)
echo "[2/2] Delivering to Telegram..."

send_telegram_doc() {
    local filepath="$1"
    local caption="$2"
    if [ -f "$filepath" ]; then
        curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendDocument" \
            -F "chat_id=${CHAT_ID}" \
            -F "document=@${filepath}" \
            -F "caption=${caption}" \
            > /dev/null 2>&1
        echo "  Sent: $(basename "$filepath")"
    else
        echo "  Skip (missing): $(basename "$filepath")"
    fi
}

# Send each report as a Telegram document
send_telegram_doc "$REPORTS_DIR/positions/$TODAY.pdf"   "Positions Report — $TODAY"
send_telegram_doc "$REPORTS_DIR/portfolio/$TODAY.pdf"   "Portfolio Report — $TODAY"
send_telegram_doc "$REPORTS_DIR/trades/$TODAY.pdf"      "Trade Activity — $TODAY"
send_telegram_doc "$REPORTS_DIR/risk/$TODAY.pdf"        "Risk Exposure — $TODAY"
send_telegram_doc "$REPORTS_DIR/signals/$TODAY.pdf"     "Signal Summary — $TODAY"
send_telegram_doc "$REPORTS_DIR/market/$TODAY.pdf"      "Market Report — $TODAY"
send_telegram_doc "$REPORTS_DIR/performance/$WEEK_TAG.pdf" "Performance — $WEEK_TAG"

# Send a brief text summary via openclaw (quick glance without opening files)
# Phase 3: query via accounts bridge table
POSITION_COUNT=$(python3 -c "
import sqlite3
conn = sqlite3.connect('crypto_data.db')
c = conn.cursor()
aids = [r[0] for r in c.execute(\"SELECT id FROM accounts WHERE portfolio_id=1 AND status='active'\").fetchall()]
if aids:
    ph = ','.join('?' * len(aids))
    c.execute(f\"SELECT COUNT(*) FROM positions WHERE account_id IN ({ph}) AND status='open'\", aids)
else:
    c.execute(\"SELECT COUNT(*) FROM positions WHERE portfolio_id=1 AND status='open'\")
print(c.fetchone()[0])
conn.close()
" 2>/dev/null || echo "?")

TRADE_COUNT=$(python3 -c "
import sqlite3
conn = sqlite3.connect('crypto_data.db')
c = conn.cursor()
aids = [r[0] for r in c.execute(\"SELECT id FROM accounts WHERE portfolio_id=1 AND status='active'\").fetchall()]
if aids:
    ph = ','.join('?' * len(aids))
    c.execute(f\"SELECT COUNT(*) FROM trades WHERE account_id IN ({ph}) AND created_at > datetime('now', '-24 hours')\", aids)
else:
    c.execute(\"SELECT COUNT(*) FROM trades WHERE portfolio_id=1 AND created_at > datetime('now', '-24 hours')\")
print(c.fetchone()[0])
conn.close()
" 2>/dev/null || echo "?")

SUMMARY="Daily Reports — $TODAY

Positions: $POSITION_COUNT open
Trades (24h): $TRADE_COUNT
Reports: 7 files delivered above

Generated by Edoras Report Engine"

# Use openclaw for the text summary
export PATH="$HOME/.nvm/versions/node/v22.22.1/bin:$PATH"
openclaw message send --channel telegram --target "$CHAT_ID" --message "$SUMMARY" 2>/dev/null || true

echo "=== Done ==="
